
const $=id=>document.getElementById(id);
const DB_NAME='ikirumi-device-ai',DB_VERSION=1;
let db, chats=[], activeChatId=null, busy=false;
function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains('chats'))d.createObjectStore('chats',{keyPath:'id'});if(!d.objectStoreNames.contains('images'))d.createObjectStore('images',{keyPath:'id'})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
function store(name,mode='readonly'){return db.transaction(name,mode).objectStore(name)}
function all(name){return new Promise((resolve,reject)=>{const r=store(name).getAll();r.onsuccess=()=>resolve(r.result||[]);r.onerror=()=>reject(r.error)})}
function put(name,value){return new Promise((resolve,reject)=>{const r=store(name,'readwrite').put(value);r.onsuccess=()=>resolve();r.onerror=()=>reject(r.error)})}
function remove(name,key){return new Promise((resolve,reject)=>{const r=store(name,'readwrite').delete(key);r.onsuccess=()=>resolve();r.onerror=()=>reject(r.error)})}
function uid(){return Date.now().toString(36)+Math.random().toString(36).slice(2,9)}
function escapeHTML(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function settings(){return {ollamaUrl:$('ollamaUrl').value.trim().replace(/\/$/,''),ollamaModel:$('ollamaModel').value.trim(),sdUrl:$('sdUrl').value.trim().replace(/\/$/,''),timeout:Math.max(30,Number($('timeout').value)||300)}}
function loadSettings(){try{const s=JSON.parse(localStorage.getItem('device-ai-settings')||'{}');if(s.ollamaUrl)$('ollamaUrl').value=s.ollamaUrl;if(s.ollamaModel)$('ollamaModel').value=s.ollamaModel;if(s.sdUrl)$('sdUrl').value=s.sdUrl;if(s.timeout)$('timeout').value=s.timeout}catch(e){}}
function saveSettings(){localStorage.setItem('device-ai-settings',JSON.stringify(settings()));$('connectionStatus').textContent='Settings saved in this browser.'}
function switchTab(name){document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));document.querySelectorAll('.tabpage').forEach(p=>p.classList.toggle('hidden',p.id!==name))}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));$('settingsBtn').onclick=()=>switchTab('settings');
function newChat(){const c={id:uid(),title:'New chat',messages:[],updated:Date.now()};chats.unshift(c);activeChatId=c.id;put('chats',c).then(renderChats);renderMessages();renderChatList()}
function activeChat(){return chats.find(c=>c.id===activeChatId)}
function renderChatList(){$('chatList').innerHTML='';chats.sort((a,b)=>b.updated-a.updated).forEach(c=>{const b=document.createElement('button');b.className='btn'+(c.id===activeChatId?' primary':'');b.textContent=c.title||'New chat';b.onclick=()=>{activeChatId=c.id;renderChatList();renderMessages()};$('chatList').appendChild(b)});if(!chats.length){const p=document.createElement('p');p.className='small';p.textContent='No chats yet.';$('chatList').appendChild(p)}}
function renderMessages(){$('messages').innerHTML='';const c=activeChat();if(!c||!c.messages.length){$('messages').innerHTML='<div class="empty">Your chats stay on this device.<br>Connect Ollama in Setup & settings to start.</div>';return}for(const m of c.messages){const d=document.createElement('div');d.className='bubble '+(m.role==='user'?'user':'ai');d.textContent=m.content;$('messages').appendChild(d)}$('messages').scrollTop=$('messages').scrollHeight}
async function sendChat(){if(busy)return;const text=$('chatInput').value.trim();if(!text)return;if(!activeChat())newChat();const c=activeChat();c.messages.push({role:'user',content:text});if(c.messages.length===1)c.title=text.slice(0,35);c.updated=Date.now();$('chatInput').value='';busy=true;renderMessages();renderChatList();$('sendChat').disabled=true;const status=document.createElement('div');status.className='bubble ai';status.textContent='Thinking locally…';$('messages').appendChild(status);try{const s=settings();const res=await fetch(s.ollamaUrl+'/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({model:s.ollamaModel,messages:c.messages.map(m=>({role:m.role,content:m.content})),stream:false})});if(!res.ok)throw new Error('Ollama returned HTTP '+res.status+'. Check the model name and local server CORS settings.');const data=await res.json();c.messages.push({role:'assistant',content:data.message?.content||'No response returned.'})}catch(e){c.messages.push({role:'assistant',content:'Could not reach your local chat model. '+e.message+'\n\nOpen Setup & settings and test the connection. The chat is still saved on this device.'})}finally{c.updated=Date.now();await put('chats',c);busy=false;$('sendChat').disabled=false;renderChatList();renderMessages()}}
$('sendChat').onclick=sendChat;$('chatInput').addEventListener('keydown',e=>{if(e.key==='Enter'&&(e.ctrlKey||e.metaKey)){e.preventDefault();sendChat()}});
$('newChat').onclick=newChat;$('deleteChat').onclick=async()=>{if(!activeChat())return;await remove('chats',activeChatId);chats=chats.filter(c=>c.id!==activeChatId);activeChatId=chats[0]?.id||null;renderChatList();renderMessages()};
async function testChat(){const s=settings();$('connectionStatus').textContent='Testing local chat…';try{const r=await fetch(s.ollamaUrl+'/api/tags');if(!r.ok)throw new Error('HTTP '+r.status);const d=await r.json();const names=(d.models||[]).map(m=>m.name);$('connectionStatus').textContent='Connected to Ollama. Models: '+(names.join(', ')||'none installed')+(names.some(n=>n===s.ollamaModel||n.startsWith(s.ollamaModel+':'))?'':' · Selected model may need to be downloaded.')}catch(e){$('connectionStatus').textContent='Could not connect: '+e.message+'. Start Ollama and allow this page origin through CORS.'}}
async function testImage(){const s=settings();$('connectionStatus').textContent='Testing local image server…';try{const r=await fetch(s.sdUrl+'/sdapi/v1/sd-models');if(!r.ok)throw new Error('HTTP '+r.status);const models=await r.json();$('connectionStatus').textContent='Connected to image server. '+models.length+' model(s) found.';$('model').innerHTML='<option value="auto">Use current model</option>';models.forEach(m=>{const o=document.createElement('option');o.value=m.title;o.textContent=m.model_name;$('model').appendChild(o)})}catch(e){$('connectionStatus').textContent='Could not connect: '+e.message+'. Start Stable Diffusion WebUI/Forge with its API enabled and configure CORS.'}}
$('testChat').onclick=testChat;$('testImage').onclick=testImage;$('saveSettings').onclick=saveSettings;
$('downloadSetupScript').onclick=async()=>{const btn=$('downloadSetupScript'),status=$('setupDownloadStatus');btn.disabled=true;status.textContent='Preparing setup script…';try{const res=await fetch('setup-windows.ps1');if(!res.ok)throw new Error('Could not fetch setup-windows.ps1 (HTTP '+res.status+'). Open Device AI from its GitHub Pages folder or download the script directly from GitHub.');const blob=await res.blob();downloadBlob(blob,'device-ai-setup-windows.ps1');status.textContent='Script downloaded. Review it, then right-click it and choose Run with PowerShell. If Windows blocks it, open PowerShell in Downloads and run: powershell -ExecutionPolicy Bypass -File .\\device-ai-setup-windows.ps1'}catch(e){status.textContent=e.message+' Direct download: github.com/123IdkGames456/ikirumi-stuff/blob/main/device-ai-text/setup-windows.ps1'}finally{btn.disabled=false}};
$('downloadChatModelBtn').onclick=async()=>{const s=settings(),model=$('downloadChatModel').value,el=$('downloadChatStatus'),btn=$('downloadChatModelBtn');btn.disabled=true;el.textContent='Connecting to Ollama and starting download of '+model+'…';try{const res=await fetch(s.ollamaUrl+'/api/pull',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({model,stream:true})});if(!res.ok)throw new Error('Ollama returned HTTP '+res.status+'. Check that Ollama is running and CORS allows this page.');if(!res.body)throw new Error('This browser cannot read the download progress stream.');const reader=res.body.getReader(),decoder=new TextDecoder();let buffer='',last='Downloading model…';while(true){const {value,done}=await reader.read();buffer+=decoder.decode(value||new Uint8Array(),{stream:!done});const lines=buffer.split(/\r?\n/);buffer=lines.pop()||'';for(const line of lines){if(!line.trim())continue;const d=JSON.parse(line);if(d.error)throw new Error(d.error);if(d.total&&d.completed){const pct=Math.floor(d.completed/d.total*100);last=(d.status||'Downloading')+' · '+pct+'% ('+Math.round(d.completed/1024/1024)+' / '+Math.round(d.total/1024/1024)+' MB)'}else if(d.status)last=d.status;el.textContent=last;}if(done)break}if(buffer.trim()){try{const d=JSON.parse(buffer);if(d.error)throw new Error(d.error)}catch(e){if(e.message!=='Unexpected end of JSON input')throw e}}$('ollamaModel').value=model;saveSettings();el.textContent='Download finished: '+model+'. Chat model selected. You can now use Chat.'}catch(e){el.textContent='Download failed: '+e.message+' Make sure Ollama is running and its CORS settings allow this page.'}finally{btn.disabled=false}};
function setStatus(text){$('genStatus').textContent=text}
async function generate(){if(busy)return;const prompt=$('prompt').value.trim();if(!prompt){setStatus('Enter a prompt first.');return}busy=true;$('generate').disabled=true;setStatus('Generating on your local image server…');$('latestImage').innerHTML='';try{const s=settings(),payload={prompt,negative_prompt:$('negative').value,width:Number($('width').value),height:Number($('height').value),steps:Number($('steps').value),batch_size:1,n_iter:1};if($('model').value!=='auto')payload.override_settings={sd_model_checkpoint:$('model').value};const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),s.timeout*1000);let res;try{res=await fetch(s.sdUrl+'/sdapi/v1/txt2img',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload),signal:controller.signal})}finally{clearTimeout(timer)}if(!res.ok)throw new Error('Image server returned HTTP '+res.status);const data=await res.json();if(!data.images?.length)throw new Error('No image was returned.');const raw=data.images[0],blob=await (await fetch('data:image/png;base64,'+raw)).blob(),record={id:uid(),prompt,negative:$('negative').value,created:Date.now(),blob,type:'image/png'};await put('images',record);const url=URL.createObjectURL(blob);$('latestImage').innerHTML='<img alt="Generated locally" style="display:block;width:100%;max-height:600px;object-fit:contain;border-radius:12px;border:1px solid var(--line)" src="'+url+'"><div class="top-actions" style="margin-top:10px"><button class="btn" id="downloadLatest">Download PNG</button><button class="btn" id="viewGallery">Open saved library</button></div>'; $('downloadLatest').onclick=()=>downloadBlob(blob,'device-ai-'+record.id+'.png');$('viewGallery').onclick=()=>{switchTab('library');renderGallery()};setStatus('Done. Image saved in your browser library.')}catch(e){setStatus((e.name==='AbortError'?'Generation timed out. ':'Could not generate: ')+e.message+' Check the local image server and CORS settings.')}finally{busy=false;$('generate').disabled=false}}
$('generate').onclick=generate;
function downloadBlob(blob,name){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1500)}
async function renderGallery(){const items=(await all('images')).sort((a,b)=>b.created-a.created);$('gallery').innerHTML='';$('galleryEmpty').classList.toggle('hidden',items.length>0);$('libraryCount').textContent=items.length+' saved image'+(items.length===1?'':'s')+' · stored on this device';for(const item of items){const url=URL.createObjectURL(item.blob),card=document.createElement('div');card.className='image-card';const img=document.createElement('img');img.src=url;img.alt=item.prompt;const caption=document.createElement('div');caption.className='small';caption.style.cssText='padding:8px;line-height:1.4';caption.textContent=item.prompt;const actions=document.createElement('div');actions.className='image-actions';const dl=document.createElement('button');dl.className='btn';dl.textContent='Download';dl.onclick=()=>downloadBlob(item.blob,'device-ai-'+item.id+'.png');const del=document.createElement('button');del.className='btn';del.textContent='Delete';del.onclick=async()=>{await remove('images',item.id);renderGallery()};actions.append(dl,del);card.append(img,caption,actions);$('gallery').appendChild(card)}}
$('exportLibrary').onclick=async()=>{const cs=await all('chats'),ims=await all('images'),out={format:'ikirumi-device-ai-backup-v1',exported:new Date().toISOString(),chats:cs,images:[]};for(const i of ims){out.images.push({...i,blob:await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(r.error);r.readAsDataURL(i.blob)})})}downloadBlob(new Blob([JSON.stringify(out)],{type:'application/json'}),'device-ai-backup.json')};
$('importBackup').onclick=()=>$('backupFile').click();$('backupFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const data=JSON.parse(await f.text());for(const c of data.chats||[])await put('chats',c);for(const i of data.images||[]){if(typeof i.blob==='string'){const b=await (await fetch(i.blob)).blob();i.blob=b}await put('images',i)}chats=await all('chats');activeChatId=chats[0]?.id||null;renderChatList();renderMessages();await renderGallery();$('connectionStatus').textContent='Backup imported.'}catch(err){$('connectionStatus').textContent='Import failed: '+err.message}e.target.value=''};
async function init(){loadSettings();try{db=await openDB();chats=await all('chats');activeChatId=chats.sort((a,b)=>b.updated-a.updated)[0]?.id||null;renderChatList();renderMessages();await renderGallery();if(navigator.storage?.estimate){const q=await navigator.storage.estimate();$('storageStatus').textContent='Using about '+Math.round((q.usage||0)/1024/1024)+' MB of '+Math.round((q.quota||0)/1024/1024)+' MB available browser storage.'}else $('storageStatus').textContent='IndexedDB available in this browser.'}catch(e){$('storageStatus').textContent='Browser storage could not be opened: '+e.message}}
init();
